# install required packages for this pipeline
install.packages("readr")
install.packages("dplyr")
install.packages("tidyr")
install.packages("tidyverse")
install.packages("fastDummies")
install.packages("emmeans")
install.packages("effectsize") 
install.packages("car")
install.packages("ggplot2")
