
thenetherlandsnorthhollandamsterdam.csv portugallisbonlisbon.csv belgiumvlgghent.csv austriaviennavienna.csv australiavicmelbourne.csv australianswnorthernrivers.csv australianswsydney.csv australiawawesternaustralia.csv: download_data.R
	Rscript download_data.R


    
