
thenetherlandsnorthhollandamsterdam.csv austriaviennavienna.csv czechrepublicpragueprague.csv portugallisbonlisbon.csv australianswnorthernrivers.csv australianswsydney.csv australiavicmelbourne.csv australiawawesternaustralia.csv: download_data.R
	Rscript download_data.R


    